language: cpp

os:
  - linux

before_install:
  - if [ `uname` == Linux ]; then sudo apt-get update -qq && sudo apt-get install -qq cmake libpcap-dev libncurses-dev

compiler:
  - clang
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
